version: '3'
silent: true

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list
    silent: false

  verify:
    desc: Run all checks equivalent to CI
    cmds:
      - echo "🧹 Checking formatting..."
      - cargo fmt --all -- --check

      - echo "🔍 Running Clippy (stable)..."
      - cargo clippy --workspace --all-targets --all-features -- -D warnings

      - echo "🧪 Running tests..."
      - |
        if command -v cargo-nextest >/dev/null 2>&1; then
          cargo nextest run --all-features \
            --hide-progress-bar \
            --failure-output=immediate \
            --success-output=never \
            --status-level=fail
          cargo test --doc --all-features --quiet
        else
          cargo test --all-features --quiet
        fi
    silent: false

  fix:
    desc: Auto-fix formatting and Clippy issues, then run tests
    cmds:
      - echo "🧹 Fixing formatting..."
      - cargo fmt --all

      - echo "🔧 Running Clippy with autofix..."
      - cargo clippy --workspace --all-targets --all-features --fix --allow-dirty --allow-staged -- -D warnings

      - echo "🧪 Running tests..."
      - |
        if command -v cargo-nextest >/dev/null 2>&1; then
          cargo nextest run --all-features \
            --hide-progress-bar \
            --failure-output=immediate \
            --success-output=never \
            --status-level=fail
          cargo test --doc --all-features --quiet
        else
          cargo test --all-features --quiet
        fi
    silent: false

  test-all:
    desc: Run all tests (unit, integration, ignored, and doctests)
    cmds:
      - echo "🧪 Running unit/integration tests..."
      - cargo test --all-features --quiet

      - echo "🧪 Running ignored tests..."
      - cargo test --all-features --quiet -- --ignored

      - echo "🧪 Running doctests..."
      - cargo test --doc --all-features --quiet
    silent: false

  bench-matrix:
    desc: Run Criterion benchmarks for match matrix performance
    cmds:
      - echo "📈 Running match_matrix Criterion benchmark..."
      - cargo bench --bench match_matrix_bench
    silent: false

  bench-matrix-rss:
    desc: Run ignored matrix perf guards and report wall time + peak RSS
    cmds:
      - echo "📉 Running matrix perf guards with RSS reporting..."
      - |
        for t in \
          perfect_match_large_perf_guard \
          contains_each_semantics_large_perf_guard \
          is_contained_in_semantics_large_perf_guard; do
          echo "=== $t ==="
          if /usr/bin/time -l cargo test --release --test match_matrix_regression_test -- --ignored --exact "$t" >/tmp/${t}.log 2>/tmp/${t}.time; then
            status=0
          else
            status=$?
          fi
          cat /tmp/${t}.time
          if [ $status -ne 0 ]; then
            if /opt/homebrew/bin/rg -q "test result: ok\\." /tmp/${t}.log && /opt/homebrew/bin/rg -q "kern.clockrate: Operation not permitted" /tmp/${t}.time; then
              echo "note: continuing despite sandbox-restricted /usr/bin/time -l"
            else
              cat /tmp/${t}.log
              exit $status
            fi
          fi
        done
    silent: false

  coverage:
    desc: Run tests and report code coverage (requires cargo-llvm-cov)
    cmds:
      - echo "🧪 Running coverage (threshold 90%)..."
      - cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info --fail-under-lines 90

  open-coverage:
    desc: Open the interactive HTML coverage report
    cmds:
      - echo "🖥️ Generating and opening HTML report..."
      - cargo llvm-cov --all-features --workspace --html --open
